module Dds {
module Example {
module Type {

    @mutable
    struct PayloadA {
        @id(1) long myNumber;
        @id(2) string myString;
    };

    @mutable
    struct Type {
        @id(1) @key long id;
        @id(2) @optional PayloadA payloadA;
    };

};
};
};
