module Dds {
module Example {
module Type {

    struct PayloadB {
        unsigned long myOtherNumber;
    };

    struct Type {
        long id;//@key
        PayloadB payloadB;//@Optional
    };

};
};
};
