module Dds {
module Example {
module Type {

    @mutable
    struct PayloadB {
        @id(1) unsigned long myOtherNumber;
    };

    @mutable
    struct Type {
        @id(1) @key long id;
        @id(3) @optional PayloadB payloadB;
    };

};
};
};
